### ISSUE TITLE
Image path correct but image name incorrect.....while running train.py

### ISSUE THREAD

**Issue by aniketghodake10** [hustvl/YOLOP#105]
when we run train.py, it doesnt read the image in AutoDriveDataset.py. 
I tried printing the path. Path is correct, but when i search that image name in the File manager, it is not there.
Any idea ??

OUTPUT:
[ WARN:0@12.734] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/ictg-7/YOLOP/dataset/bdd100k_images_10k/bdd100k/images/10k/train/7ef977f6-0da26205.jpg'): can't open/read file: check file path/integrity
    data.reraise()
  File "/home/ictg-7/.local/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ictg-7/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ictg-7/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ictg-7/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ictg-7/YOLOP/lib/dataset/AutoDriveDataset.py", line 106, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by aniketghodake10** [comment]
Re-downloading dataset solved the issue
