### ISSUE TITLE
转onnx模型bug

### ISSUE THREAD

**Issue by Salary-only-17k** [hustvl/YOLOP#148]
你好，使用的你export_onnx.py对end_to_end.pth模型转化为onnx模型遇到3个问题。
- 1 转onnx模型报错，但是转成功一个onnx文件
```bash
read failed
Traceback (most recent call last):
  File "export_onnx.py", line 194, in <module>
    raise e
  File "export_onnx.py", line 184, in <module>
    sess = ort.InferenceSession(onnx_path)
  File "/media/cc/watermelon/miniconda3/envs/env_torch/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/media/cc/watermelon/miniconda3/envs/env_torch/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Mul_1350) Op (Mul) [ShapeInferenceError] Incompatible dimensions
```
- 2 hardhtanh激活函数结构变了，具体是div节点的位置不对
- 3 det-head的结构变了。并且报错，Mul_1350节点有问题。

怎么解决？

**Comment by Salary-only-17k** [comment]
使用的是common2.py文件
