### ISSUE TITLE
When i try to test the model generalization with coco datasets, I got this error:RuntimeError: Input and output sizes should be greater than 0, but got input (H: 426, W: 640) output (H: 0, W: 0)

### ISSUE THREAD

**Issue by Roly-Yang** [hustvl/YOLOP#166]
When i try to test the model generalization with coco datasets, I got this error:
--------------------------------------------------------------------------------------------------------
UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
Traceback (most recent call last):
  File "tools/demo.py", line 186, in <module>
    detect(cfg,opt)
  File "tools/demo.py", line 118, in detect
    da_seg_mask = torch.nn.functional.interpolate(da_predict, scale_factor=int(1/ratio), mode='bilinear')
  File "/home/xxx/J/Anaconda3/envs/yolo_p/lib/python3.7/site-packages/torch/nn/functional.py", line 3151, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 426, W: 640) output (H: 0, W: 0)
---------------------------------------------------------------------------------------------------------------
the command I use: python -X faulthandler tools/demo.py --source ./inference/coco_car
---------------------------------------------------------------------------------------------------------------
The folder coco_car contains some inconsistent resolution pictures  from coco2017, which is mainly about traffic scenes.
---------------------------------------------------------------------------------------------------------------
Any help would be appreciated.

**Comment by QinghuanWei** [comment]
i meet the same condition,maybe the type of images is incorrect
