### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by simplew2011** [hustvl/YOLOP#186]
use release weight to eval, Lane Detection Result is wrong.
![image](https://user-images.githubusercontent.com/66729924/234468512-a50721aa-5467-46c1-9d74-b3fc6b030dd6.png)

**Comment by realTravisYou** [comment]
Hello, I use `python tools/test.py --weights weights/End-to-end.pth` command, but I encounter this error. Do you know how to solve it? Thank you very much!

Traceback (most recent call last):
  File "/home/travis/YOLOP/tools/test.py", line 153, in <module>
    main()
  File "/home/travis/YOLOP/tools/test.py", line 86, in main
    checkpoint = torch.load(checkpoint_file)
  File "/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/serialization.py", line 473, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/serialization.py", line 458, in __init__
    _check_seekable(buffer)
  File "/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/serialization.py", line 567, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/serialization.py", line 560, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'list' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
