### ISSUE TITLE
No such file or directory, Error.

### ISSUE THREAD

**Issue by Hagonata** [hustvl/YOLOP#191]
```
load model to device
begin to load data
building database...
  0%|                                                                                                                                                                                   | 0/70000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/train.py", line 395, in <module>
    main()
  File "tools/train.py", line 261, in main
    train_dataset = eval('dataset.' + cfg.DATASET.DATASET)(
  File "/home/user/YOLOP/lib/dataset/bdd.py", line 13, in __init__
    self.db = self._get_db()
  File "/home/user/YOLOP/lib/dataset/bdd.py", line 37, in _get_db
    with open(label_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/user/LaCie/DataSet/YOLOP/det_annotation/train/1f864b3f-a736fa8b.json'
```

But check and I have this file in the all folders. What a problem can be?

**Comment by santhanakrishnan26** [comment]
Verify the data path (DATAROOT, LABELROOT, MASKROOT, LANEROOT) from the default.py file and also verify the dataset directory structure.

**Comment by shfunc** [comment]
> Verify the data path (DATAROOT, LABELROOT, MASKROOT, LANEROOT) from the default.py file and also verify the dataset directory structure.

All good now, I already forgot about this issue, sorry.
