### ISSUE TITLE
torchvision::nms 函数无法在 CUDA 后端运行

### ISSUE THREAD

**Issue by weigengming** [hustvl/YOLOP#217]
我是在算力云平台跑的，但运行完一轮后报错：
Traceback (most recent call last):
File "tools/train.py", line 395, in <module>
main()
File "tools/train.py", line 330, in main
da_segment_results,ll_segment_results,detect_results, total_loss,maps, times = validate(
File "/root/YOLOP-main/lib/core/function.py", line 258, in validate
output = non_max_suppression(inf_out, conf_thres= config.TEST.NMS_CONF_THRESHOLD, iou_thres=config.TEST.NMS_IOU_THRESHOLD, labels=lb)
File "/root/YOLOP-main/lib/core/general.py", line 169, in non_max_suppression
i = torchvision.ops.nms(boxes, scores, iou_thres) # NMS
File "/root/miniconda3/lib/python3.8/site-packages/torchvision/ops/boxes.py", line 42, in nms
return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
RuntimeError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 'torchvision::nms' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].
经搜索后是说函数没法在CUDA后端运行，如何解决

**Comment by weigengming** [comment]
环境是：
PyTorch  1.7.0
Python  3.8(ubuntu18.04)
Cuda  11.0

**Comment by weigengming** [comment]
已解决。https://blog.csdn.net/weixin_51179975/article/details/119082342

**Comment by realTravisYou** [comment]
/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538438429/work/aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                                                                    | 0/500 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/travis/YOLOP/tools/test.py", line 157, in <module>
    main()
  File "/home/travis/YOLOP/tools/test.py", line 137, in main
    da_segment_results,ll_segment_results,detect_results, total_loss,maps, times = validate(
  File "/home/travis/YOLOP/lib/core/function.py", line 247, in validate
    total_loss, head_losses = criterion((train_out,da_seg_out, ll_seg_out), target, shapes,model)   #Compute loss
  File "/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/travis/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/travis/YOLOP/lib/core/loss.py", line 50, in forward
    total_loss, head_losses = self._forward_impl(head_fields, head_targets, shapes, model)
  File "/home/travis/YOLOP/lib/core/loss.py", line 70, in _forward_impl
    tcls, tbox, indices, anchors = build_targets(cfg, predictions[0], targets[0], model)  # targets
  File "/home/travis/YOLOP/lib/core/postprocess.py", line 74, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int

你好，在执行tools/test.py时，出现了这个问题，请问如何解决？
