### ISSUE TITLE
验证失败

### ISSUE THREAD

**Issue by realTravisYou** [hustvl/YOLOP#218]
(yolop) travis@DESKTOP-L6HSFEE:~/YOLOP$ python tools/test.py --weights weights/End-to-end.pth
=> creating runs/BddDataset/_2024-09-24-09-46
Namespace(conf_thres=0.001, iou_thres=0.6, logDir='runs/', modelDir='', weights=['weights/End-to-end.pth'])
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  COLOR_RGB: False
  DATAROOT: /home/travis/YOLOP/data/images
  DATASET: BddDataset
  DATA_FORMAT: jpg
  FLIP: True
  HSV_H: 0.015
  HSV_S: 0.7
  HSV_V: 0.4
  LABELROOT: /home/travis/YOLOP/data/det_annotations
  LANEROOT: /home/travis/YOLOP/data/ll_seg_annotations
  MASKROOT: /home/travis/YOLOP/data/da_seg_annotations
  ORG_IMG_SIZE: [720, 1280]
  ROT_FACTOR: 10
  SCALE_FACTOR: 0.25
  SELECT_DATA: False
  SHEAR: 0.0
  TEST_SET: val
  TRAIN_SET: train
  TRANSLATE: 0.1
DEBUG: False
GPUS: (0, 1)
LOG_DIR: runs/
LOSS:
  BOX_GAIN: 0.05
  CLS_GAIN: 0.5
  CLS_POS_WEIGHT: 1.0
  DA_SEG_GAIN: 0.2
  FL_GAMMA: 0.0
  LL_IOU_GAIN: 0.2
  LL_SEG_GAIN: 0.2
  LOSS_NAME:
  MULTI_HEAD_LAMBDA: None
  OBJ_GAIN: 1.0
  OBJ_POS_WEIGHT: 1.0
  SEG_POS_WEIGHT: 1.0
MODEL:
  EXTRA:

  HEADS_NAME: ['']
  IMAGE_SIZE: [640, 640]
  NAME:
  PRETRAINED:
  PRETRAINED_DET:
  STRU_WITHSHARE: False
NEED_AUTOANCHOR: True
PIN_MEMORY: False
PRINT_FREQ: 20
TEST:
  BATCH_SIZE_PER_GPU: 4
  MODEL_FILE:
  NMS_CONF_THRESHOLD: 0.001
  NMS_IOU_THRESHOLD: 0.6
  PLOTS: True
  SAVE_JSON: False
  SAVE_TXT: False
TRAIN:
  ANCHOR_THRESHOLD: 4.0
  BATCH_SIZE_PER_GPU: 8
  BEGIN_EPOCH: 0
  DET_ONLY: True
  DRIVABLE_ONLY: False
  ENC_DET_ONLY: False
  ENC_SEG_ONLY: False
  END_EPOCH: 240
  GAMMA1: 0.99
  GAMMA2: 0.0
  IOU_THRESHOLD: 0.2
  LANE_ONLY: False
  LR0: 0.001
  LRF: 0.2
  MOMENTUM: 0.937
  NESTEROV: True
  OPTIMIZER: adam
  PLOT: True
  SEG_ONLY: False
  SHUFFLE: True
  VAL_FREQ: 1
  WARMUP_BIASE_LR: 0.1
  WARMUP_EPOCHS: 3.0
  WARMUP_MOMENTUM: 0.8
  WD: 0.0005
WORKERS: 8
num_seg_class: 2
begin to bulid up model...
Using torch 1.7.0 CUDA:0 (NVIDIA GeForce RTX 4060, 8187MB)

finish build model
=> loading checkpoint '['weights/End-to-end.pth']'
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/yolop/lib/python3.8/site-packages/torch/serialization.py", line 308, in _check_seekable
    f.seek(f.tell())
AttributeError: 'list' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 86, in main
    checkpoint = torch.load(checkpoint_file)
  File "/home/travis/miniconda3/envs/yolop/lib/python3.8/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/travis/miniconda3/envs/yolop/lib/python3.8/site-packages/torch/serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/home/travis/miniconda3/envs/yolop/lib/python3.8/site-packages/torch/serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "/home/travis/miniconda3/envs/yolop/lib/python3.8/site-packages/torch/serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/travis/miniconda3/envs/yolop/lib/python3.8/site-packages/torch/serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'list' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

请问这个是什么原因啊？

**Comment by realTravisYou** [comment]
I have changed this line in test.py.
`checkpoint = torch.load(checkpoint_file[0])`
