### ISSUE TITLE
Error on Executing demo.py

### ISSUE THREAD

**Issue by avp24** [hustvl/YOLOP#223]
Hi

I am executing the tools/demo.py script as per below command - 
**python tools/demo.py --source inference/videos/CARELE_25_Scenario_draft_v1_15_Nov.mp4 --save-dir=output/**
I observe error : 
python tools/demo.py --source inference/videos/CARELE_25_Scenario_draft_v1_15_Nov.mp4 --save-dir=output/
['/home/adas6/sample_apps/conda/coe_yolov8/YoloP_Coe/YOLOP/tools', '/home/adas6/anaconda3/envs/YoloP_coe/lib/python38.zip', '/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8', '/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/lib-dynload', '/home/adas6/.local/lib/python3.8/site-packages', '/home/adas6/anaconda3/envs/yolov8_coe/lib/python3.8/site-packages/setuptools/_vendor', '/home/adas6/.local/lib/python3.8/site-packages/torchvision-0.16.0-py3.8-linux-aarch64.egg', '/home/adas6/.local/lib/python3.8/site-packages/requests-2.32.3-py3.8.egg', '/home/adas6/.local/lib/python3.8/site-packages/certifi-2024.12.14-py3.8.egg', '/home/adas6/.local/lib/python3.8/site-packages/urllib3-2.2.3-py3.8.egg', '/home/adas6/.local/lib/python3.8/site-packages/idna-3.10-py3.8.egg', '/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages', '/home/adas6/sample_apps/conda/coe_yolov8/YoloP_Coe/YOLOP']
Traceback (most recent call last):
  File "/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 45, in <module>
    from ._check_build import check_build  # noqa
ImportError: /home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/demo.py", line 29, in <module>
    from lib.core.postprocess import morphological_process, connect_lane
  File "/home/adas6/sample_apps/conda/coe_yolov8/YoloP_Coe/YOLOP/lib/core/postprocess.py", line 6, in <module>
    from sklearn.cluster import DBSCAN
  File "/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__init__.py", line 79, in <module>
    from . import (
  File "/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 47, in <module>
    raise_build_error(e)
  File "/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: /home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
___________________________________________________________________________
Contents of /home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__check_build:
__init__.py               _check_build.cpython-38-aarch64-linux-gnu.so__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

Steps Followed : 
a) Cloned the repo.
b) Created an virtual environment using anaconda for python 3.8.11
c) Installed all the packages using requirement.txt
d) Installed torch and torchvision compatible to cuda-11.4 such that GPU is detected.

**Comment by avp24** [comment]
This error got resolved using 
export LD_PRELOAD=/home/adas6/anaconda3/envs/YoloP_coe/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0
