### ISSUE TITLE
AssertionError: Invalid type

### ISSUE THREAD

**Issue by Jasonshao0123** [hustvl/YOLOP#37]
When I run python tools/demo.py --source ./inference/images/street.jpg
it appeared:
Traceback (most recent call last):
  File "tools/demo.py", line 21, in <module>
    from lib.config import cfg
  File "/home/zzj/Projects/YOLOP/lib/config/__init__.py", line 1, in <module>
    from .default import _C as cfg
  File "/home/zzj/Projects/YOLOP/lib/config/default.py", line 38, in <module>
    _C.LOSS.MULTI_HEAD_LAMBDA = None
  File "/home/zzj/anaconda3/envs/yolov5/lib/python3.8/site-packages/yacs/config.py", line 155, in __setattr__
    _assert_with_logging(
  File "/home/zzj/anaconda3/envs/yolov5/lib/python3.8/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key MULTI_HEAD_LAMBDA; valid types = {<class 'list'>, <class 'tuple'>, <class 'int'>, <class 'bool'>, <class 'str'>, <class 'float'>}

I changed the image name .The new name is 'street'. 
我实在没能自己解决，麻烦作者看下是哪里出现了问题，应该如何解决呢？

**Comment by PigLogic-Cyber** [comment]
Try to change '_C.LOSS.MULTI_HEAD_LAMBDA = None' to be '_C.LOSS.MULTI_HEAD_LAMBDA = False', works for me, good luck :-)

**Comment by Jasonshao0123** [comment]
Thanks 原因是torch版本没对

**Comment by Jasonshao0123** [comment]
> Try to change '_C.LOSS.MULTI_HEAD_LAMBDA = None' to be '_C.LOSS.MULTI_HEAD_LAMBDA = False', works for me, good luck :-)

thanks 发现是torch版本没对
