### ISSUE TITLE
Issues while running train.py

### ISSUE THREAD

**Issue by jptalledo10** [hustvl/YOLOP#45]
Just checking if there is any suggestions/advise to go around this error:

RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 7.79 GiB total capacity; 6.47 GiB already allocated; 37.38 MiB free; 6.53 GiB reserved in total by PyTorch)

Traceback (most recent call last):
  File "tools/train.py", line 395, in <module>
    main()
  File "tools/train.py", line 323, in main
    epoch, num_batch, num_warmup, writer_dict, logger, device, rank)
  File "/home/jvilela/YOLOP/lib/core/function.py", line 76, in train
    outputs = model(input)
  File "/home/jvilela/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jvilela/YOLOP/lib/models/YOLOP.py", line 555, in forward
    x = block(x)
  File "/home/jvilela/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jvilela/YOLOP/lib/models/common.py", line 132, in forward
    return self.cv4(self.act(self.bn(torch.cat((y1, y2), dim=1))))
  File "/home/jvilela/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jvilela/YOLOP/lib/models/common.py", line 97, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/jvilela/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jvilela/YOLOP/lib/models/common.py", line 82, in forward
    return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX
  File "/home/jvilela/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1188, in hardtanh
    result = torch._C._nn.hardtanh(input, min_val, max_val)
RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 7.79 GiB total capacity; 6.47 GiB already allocated; 37.38 MiB free; 6.53 GiB reserved in total by PyTorch)

jvilela@soads-gpu-4:~/YOLOP$ nvidia-smi
Wed Oct 13 19:41:45 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:65:00.0  On |                  N/A |
| 18%   38C    P8    13W / 250W |    280MiB /  7973MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1955      G   /usr/lib/xorg/Xorg                 18MiB |
|    0   N/A  N/A      2076      G   /usr/bin/gnome-shell               49MiB |
|    0   N/A  N/A      4417      G   /usr/lib/xorg/Xorg                105MiB |
|    0   N/A  N/A      4578      G   /usr/bin/gnome-shell               75MiB |
|    0   N/A  N/A      5283      G   ...AAAAAAAAA= --shared-files       27MiB |
+-----------------------------------------------------------------------------+

**Comment by Yunboxun** [comment]
> I'm also having issue when executing train.py The following is the description of the Error :
> 
> Traceback (most recent call last): File "C:/Users/Wei/torch/YOLOP-main/tools/train.py", line 397, in main() File "C:/Users/Wei/torch/YOLOP-main/tools/train.py", line 325, in main epoch, num_batch, num_warmup, writer_dict, logger, device, rank) File "C:\Users\Wei\torch\YOLOP-main\lib\core\function.py", line 51, in train for i, (input, target, paths, shapes) in enumerate(train_loader): File "C:\Users\Wei\torch\YOLOP-main\lib\utils\utils.py", line 153, in **iter** return BackgroundGenerator(super().**iter**()) File "c:\users\wei\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 359, in **iter** return self._get_iterator() File "c:\users\wei\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "c:\users\wei\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 918, in **init** w.start() File "c:\users\wei\anaconda3\lib\multiprocessing\process.py", line 112, in start self._popen = self._Popen(self) File "c:\users\wei\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "c:\users\wei\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen return Popen(process_obj) File "c:\users\wei\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in **init** reduction.dump(process_obj, to_child) File "c:\users\wei\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) TypeError: can't pickle generator objects

Have you solved this problem？
