### ISSUE TITLE
Issue while running train.py

### ISSUE THREAD

**Issue by 108318139** [hustvl/YOLOP#97]
I have an issue while running train.py
The following is the description of the Error :

Traceback (most recent call last):
File "C:/Users/Wei/torch/YOLOP-main/tools/train.py", line 397, in
main()
File "C:/Users/Wei/torch/YOLOP-main/tools/train.py", line 325, in main
epoch, num_batch, num_warmup, writer_dict, logger, device, rank)
File "C:\Users\Wei\torch\YOLOP-main\lib\core\function.py", line 51, in train
for i, (input, target, paths, shapes) in enumerate(train_loader):
File "C:\Users\Wei\torch\YOLOP-main\lib\utils\utils.py", line 153, in iter
return BackgroundGenerator(super().iter())
File "c:\users\wei\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 359, in iter
return self._get_iterator()
File "c:\users\wei\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "c:\users\wei\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 918, in init
w.start()
File "c:\users\wei\anaconda3\lib\multiprocessing\process.py", line 112, in start
self._popen = self._Popen(self)
File "c:\users\wei\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "c:\users\wei\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "c:\users\wei\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in init
reduction.dump(process_obj, to_child)
File "c:\users\wei\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects

**Comment by gaurav82692** [comment]
Getting same error please help

**Comment by Yunboxun** [comment]
Do you train on CPU or GPU？

**Comment by Yunboxun** [comment]
![20220509171456](https://user-images.githubusercontent.com/77442461/167379293-2f8e31ba-92d1-46c5-a9b9-44a8e08eb7fe.png)
把这个数改成0，就能运行了，好像是线程的问题，简单来说就是cpu太拉了兄弟们

**Comment by seenthestars** [comment]
How to use gpu run train.py?
